# Copyright (c) 2021 Ecosoft Co., Ltd.

site_name: Your Project Name
copyright: Copyright &copy; 2021 Ecosoft Co., Ltd.
repo_url: https://github.com/ecosoft-odoo/eco_mkdocs  # Add edit on github link
edit_uri: edit/master/docs  # Point to master branch
theme: readthedocs
nav:  # Content organization
    - Home: index.md
    #- Overview: overview.md
    - program allocaiton : budget/1_program_allocation/allocation.md
    - phasing plan : budget/2_phasing_plan/phasing_plan.md
    - phansing plan in system : budget/2_phasing_plan/phasing_plan_manual.md
markdown_extensions:
    - toc:  # For link for hearders, H1, H2, etc.
        permalink: "#"  
    - admonition   # For !!! Note box
plugins:
    - search
    - with-pdf:  # More params -> https://pypi.org/project/mkdocs-with-pdf/
        cover_title: My Project Documentation
        cover_subtitle: Odoo ERP for Some Company
        cover_logo: ecosoft.png
        author: Kitti U. <kittiu@ecosoft.co.th>

